use_frameworks!

platform :ios, '9.0'

target 'HJTextView_Example' do
  pod 'HJTextView', :path => '../'

  target 'HJTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
